import "../styles/globals.css";
import Head from "next/head";
import type { AppType } from "next/dist/shared/lib/utils";
import bg from "../../public/bg.jpg";

const menuItems = [
  { name: "about", link: "/about" },
  { name: "discography", link: "/" },
  { name: "music", link: "/" },
  { name: "videos", link: "/" },
  { name: "contact", link: "/" },
];

const Menu = () => (
  <div className="flex">
    {menuItems.map((mi) => (
      <a
        key={mi.name}
        href={mi.link}
        className="my-4 mx-4 cursor-pointer py-4 px-4 text-xl font-semibold uppercase text-gray-100 drop-shadow-sm transition-all hover:scale-105 hover:text-slate-800"
      >
        {mi.name}
      </a>
    ))}
  </div>
);

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>John Lecter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen w-full flex-col items-center">
        <div className="absolute -z-10 min-h-full w-full overflow-hidden">
          <div className="absolute z-10 min-h-screen w-full bg-slate-500 opacity-40"></div>
          <div
            className="min-h-screen w-full animate-fly-in-out bg-cover bg-center"
            style={{ backgroundImage: `url(${bg.src})` }}
          ></div>
        </div>
        <Menu />
        <Component {...pageProps} />
      </div>
      <footer className="bg-slate-800 py-8 text-center text-sm text-slate-500">
        {`© ${new Date().getFullYear()} John Lecter. All Rights Reserved`}
      </footer>
    </>
  );
};

export default MyApp;
