import type { NextPage } from "next";
import Head from "next/head";
import bg from "../../public/bg.jpg";

const menuItems = [
  { name: "about" },
  { name: "discography" },
  { name: "music" },
  { name: "videos" },
  { name: "contact" },
];

const Menu = () => (
  <div className="flex">
    {menuItems.map((mi) => (
      <button
        key={mi.name}
        className="my-4 mx-4 py-4 px-4 text-xl font-semibold uppercase text-gray-100 drop-shadow-sm transition-all hover:scale-105 hover:text-slate-800"
      >
        {mi.name}
      </button>
    ))}
  </div>
);

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>John Lecter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen w-full flex-col items-center">
        <div className="absolute -z-10 min-h-full w-full overflow-hidden">
          <div className="absolute z-10 min-h-screen w-full bg-slate-500 opacity-40"></div>
          <div
            className="min-h-screen w-full animate-fly-in-out bg-cover bg-center"
            style={{ backgroundImage: `url(${bg.src})` }}
          ></div>
        </div>
        <Menu />
        <h1 className="flex min-h-full flex-grow items-center text-5xl font-extrabold leading-normal text-gray-100 md:text-[5rem]">
          John Lecter.
        </h1>
      </main>
      <footer className="bg-slate-800 text-sm text-center text-slate-500 py-8">
        {`© ${new Date().getFullYear()} John Lecter. All Rights Reserved`}
      </footer>
    </>
  );
};

export default Home;
