import type { NextPage } from "next";
import Head from "next/head";
import bg from "../../public/bg.jpg";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen w-full items-center justify-center">
        <div className="absolute min-h-full w-full overflow-hidden">
          <div className="absolute min-h-screen z-10 w-full bg-slate-500 opacity-40"></div>
          <div
            className="min-h-screen w-full animate-fly-in-out bg-cover bg-center"
            style={{ backgroundImage: `url(${bg.src})` }}
          ></div>
        </div>
        <h1 className="text-5xl font-extrabold leading-normal z-10 text-gray-100 md:text-[5rem]">
          John Lecter.
        </h1>
      </main>
    </>
  );
};

export default Home;
